### ISSUE TITLE
Create fails for ASG - Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by sompnd** [aws-quickstart/quickstart-linux-bastion#35] opened 2018-06-06 13:39 UTC
Hi, 

I am running the stack for existing VPC in eu-central-1. Unfortunately every time it fails when creating the autoscaling group with the message: 

_BastionAutoScalingGroup Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement_ 

I am using all the default values apart from the QSS3KeyPrefix value. 
Thanks.

**Comment by agamzn** [comment] 2018-07-05 16:11
What OS Are you using with your stack? Are there any logs available from the instance before you terminated it?

**Comment by pnomolos** [comment] 2018-07-11 03:15
This is likely due to the fact that AWS Auto Scaling is only available in Ireland (of the European regions), I would think?  I'm running in to the same issue with an ASG in ca-central-1 and I believe it's the same problem.

**Comment by rniksch** [comment] 2018-07-26 18:34
I have not been able to replicate this issue.
I have launched thus quick start in a new VPC as well as existing VPCs in us-west-1, us-east-1 eu-central and ca-central. In all tests the stack completes as expected and auto scaling behaves as expected. I can confirm that the above is not related to Autoscaling support in eu-central or ca-central.

At this stage I suspect something in the existing VPC being launched into may be hindering connectivity for the CFN-init process.

Please would you confirm if this is still manifesting.

**Comment by vasylk** [comment] 2018-08-28 07:56
I can confirm the same behaviour as in the starting post.
Region: eu-central-1
VPC: Default
Subnet1: Default in A-AZ
Subnet2: Default in B-AZ

The rest of the paremeters are almost by default. See the attached screenshot.

Stack creation error:
**Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requiremen**

![screenshot from 2018-08-28 09-44-08](https://user-images.githubusercontent.com/19506086/44708839-73dea980-aaa8-11e8-96b9-0177aec6fa8b.png)

**Comment by hierynomus** [comment] 2018-11-06 09:52
@sompnd We ran into the same, also indeed only changing the `QSS3KeyPrefix`. We managed to fix it by ensuring that the `QSS3KeyPrefix` ends with a `/`! If it doesn't the URL of the init script does not match up and subsequently the bastion host will not initialize. I've submitted #50 to change the regex to validate that the last character is a `/`.

**Comment by roc1** [comment] 2019-03-16 17:11
Couldn't get around this error :-(

**Comment by tomiszili** [comment] 2019-08-23 12:55
This bug is still in the script, if I run from my own S3 bucket. Even if the `QSSKeyPrefix` ends with `'/'`.  I run the quickstart-eks nested stack but it fails because this error.

**Comment by schottsfired** [comment] 2019-08-23 13:03
https://github.com/aws-quickstart/quickstart-amazon-eks/issues/9 looks related. I was able to work around it using the technique mentioned in the ticket.

**Comment by tomiszili** [comment] 2019-08-23 13:35
> [aws-quickstart/quickstart-amazon-eks#9](https://github.com/aws-quickstart/quickstart-amazon-eks/issues/9) looks related. I was able to work around it using the technique mentioned in the ticket.

Thanks @schottsfired!
I copied the entire eks-quickstart repo with submodules to my S3 bucket, and then ran the new VPC master template from CloudFormation and fails. But if I run the guide https://docs.aws.amazon.com/quickstart/latest/amazon-eks-architecture/welcome.html completes properly.

**Comment by vsnyc** [comment] 2019-08-23 13:42
> This bug is still in the script, if I run from my own S3 bucket. Even if the `QSSKeyPrefix` ends with `'/'`. I run the quickstart-eks nested stack but it fails because this error.

S3 sig v2 is on the path to deprecation, however at this time cfn-init does not make sig v4 requests when fetching files from S3. When you test quick starts with taskcat and have used the `"$[taskcat_autobucket]"` token for `QSS3BucketName` parameter, you'll run into this error if you have not passed in `--enable-sig-v2` argument to taskcat, since taskcat applies a bucket policy on the autogenerated bucket that disables sig v2. See [source code](https://github.com/aws-quickstart/taskcat/blob/8df37d09380471a334d718f0ebda0949f9776f56/taskcat/stacker.py#L426-L479).

There are two options when testing with taskcat:
1. pass `--enable-sig-v2` when testing from the autogenerated bucket
2. Use your own bucket with taskcat and ensure it doesn't have any policies that disallow sig v2. To do this you can add `s3bucket: <your-bucket-name>` property in the `global` section in taskcat.yml, and also use the same bucket as the value for `QSS3BucketName` parameter.

**Comment by vsnyc** [comment] 2019-08-23 13:45
See also comment https://github.com/aws-quickstart/quickstart-linux-bastion/issues/44#issuecomment-510317391 and a [screen recording](https://www.youtube.com/watch?v=KCdMlIezkUg) I had created for this issue.

**Comment by tomiszili** [comment] 2019-08-23 14:17
Is it possible to create this stack without taskcat? I can't find any taskcat script inside the quickguide CFN files which could run during the stack creation and indicate this problem. 
What is the main difference if i'm using the native AWS deploy with default parameters or using the eks-quickstart repo?

**Comment by vsnyc** [comment] 2019-08-23 14:39
Yes, absolutely. Taskcat is not a requirement. Please follow the instructions on how to run from your own bucket in our [contributor's guide](https://aws-quickstart.github.io/option1.html). 

> What is the main difference if i'm using the native AWS deploy with default parameters or using the eks-quickstart repo?

There is no difference as far as the bastion stack goes, it is just launched as a nested stack. The three issues I most commonly see are 1) stack failing due to sig v2 errors with cfn-init ; 2) repo not being recursively cloned and running into errors at the time the nested stack is launched. 

I am happy to create a screen recording for EKS Quick Start if it helps.

Also, looking at the original issue reported "I am using all the default values apart from the QSS3KeyPrefix value." - I have to assume that QSS3BucketName was different as well, else it would never work.

**Comment by tomiszili** [comment] 2019-08-23 15:43
Thanks for your support @vsnyc!

> Also, looking at the original issue reported "I am using all the default values apart from the QSS3KeyPrefix value." - I have to assume that QSS3BucketName was different as well, else it would never work.

Yes both of the parameters were set related to my S3 bucket structure.

If it is possible please record an EKS Quick Start with CloudFormation and with a new S3 bucket. I'm getting really desperate about the failed stack creation, because I did everthing as the contributor's guide says and my whole bucket is public and objects as well.

**Comment by tomiszili** [comment] 2019-08-27 08:30
@vsnyc thanks for the video and support. 
I find one solution for this problem, the bucket URL in https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks.template.yaml#L244 should be: `https://s3.${S3BucketRegion}.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}scripts/bastion_bootstrap.sh`

Currently i don't know how to get the region of a bucket from cloudformation automatically, so i hardcoded it in the yaml template like this: `https://s3.eu-central-1.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}scripts/bastion_bootstrap.sh`

I didn't try but an idea: maybe the bastion instance should download it by linux commands with latest awscli instead of `AWS::CloudFormation::Init:config:files:source` in the template.

**Comment by avattathil** [comment] 2019-10-15 21:56
Version 2 will use cfn-init calls

You can get the region using a Conditional like so:

### Add conditional
```
Conditions:
  GovCloudCondition: !Equals
    - !Ref 'AWS::Region'
    - us-gov-west-1

```
### Build the s3 path using conditional
```
      UserData: !Base64
        Fn::Sub:
          - |
            #!/bin/bash -x
            https://${QSS3BucketName}.${S3Region}.amazonaws.com/${QSS3KeyPrefix}
          -
            S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, s3] 
```

**Comment by avattathil** [comment] 2019-10-15 22:12
Closing this issue.  Please track [version 2](https://github.com/aws-quickstart/quickstart-linux-bastion/projects/1) for progress. If any issues are still open at release please open a new issue

**Closed by avattathil** 2019-10-15 22:12 UTC

**Comment by schottsfired** [comment] 2020-05-28 18:19
I hit this error message last week in our Quick Start, and fixed it with https://github.com/aws-quickstart/quickstart-cloudbees-core/commit/6902e697c7419677bafd80425260aa569278fe3a. The problem was that CFN never received the signal that the instance was running. Hope it helps!

**Comment by nathalieDOXA** [comment] 2020-06-16 15:14
> I hit this error message last week in our Quick Start, and fixed it with [aws-quickstart/quickstart-cloudbees-core@6902e69](https://github.com/aws-quickstart/quickstart-cloudbees-core/commit/6902e697c7419677bafd80425260aa569278fe3a). The problem was that CFN never received the signal that the instance was running. Hope it helps!

Hi @schottsfired, could you help me explain more on that? It seems the linux-bastion is different from the cloudbees-core, maybe my knowledge is limited to that.
Thank you in advance.

**Comment by schottsfired** [comment] 2020-06-16 19:51
Hi @nathalieDOXA, for sure `quickstart-cloudbees-core` is a separate project, but we interact with `quickstart-linux-bastion` via submodules. Our QS submodules `quickstart-amazon-eks`, and that QS submodules `quickstart-linux-bastion` (and `quickstart-aws-vpc`).

**Comment by eyedean** [comment] 2021-01-19 06:53
It happened to me and after an hour of debugging, I found that the "banner text" cannot be a simple "`welcome to bastion!` string as it's directly passed as a bash argument!

To debug:
1. Disable rollback
2. When the Instance is up (even during "initializing...") SSH into it and do `cat /var/log/cfn-init.log`

Mine was:
```
...
2021-01-19 06:37:04,609 [DEBUG] Running command b-bootstrap
2021-01-19 06:37:04,609 [DEBUG] No test for command b-bootstrap
2021-01-19 06:37:07,672 [ERROR] Command b-bootstrap (./bastion_bootstrap.sh --banner Welcome to The Bastion! --enable true --tcp-forwarding true --x11-forwarding false) failed
2021-01-19 06:37:07,672 [DEBUG] Command b-bootstrap output: checkos Ended
which: no aws in ((null))
...
```

Maybe in the future, a validator (like the one for `RemoteAccessCIDR`) in the template would save other folks' time debugging.

Hope it helps. :)
