### ISSUE TITLE
Ubuntu 16.04 incompatibility with aws-cfn-bootstrap 1.4

### ISSUE THREAD

**Issue by steve-ochoa** [aws-quickstart/quickstart-linux-bastion#33] opened 2018-05-02 21:11 UTC
Hello there, 
I just tried launching a new Bastion on the Ubuntu 16.04 AMI (region: us-east-1) defined in the latest CFN template in this repo. I have been using a slightly modified version of the template/script provided here to get custom Banner text to download properly from S3. 

The Problem:
Cloudformation create-stack fails when deploying the AutoScalingGroup. 
Cloudformation error: "Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement"

EC2 Instance System log:
"[   89.696286] cloud-init[1339]: Finished processing dependencies for aws-cfn-bootstrap==1.4
[   90.109857] cloud-init[1339]: Error occurred during build: Command b-bootstrap failed
"

Internet connectivity is not an issue as the instance was able to download all the dependencies and the aws-cfn-boostrap lib itself. 

The Fix: Re-launching with the Ubuntu 14.04 AMI. 

I have reproduced the issue several times. I have not dug into the instance logs to investigate why it is failing. My previous CFN Stack was launched on March 31st with no issues using 16.04 LTS AMI. It was only today that I encountered this issue. 

Thanks for the robust Bastion templates/scripts, I love using them and I learned alot from reading through the code. Hopefully this helps anyone else trying to launch with the Ubuntu 16.04 LTS AMI.

**Comment by agamzn** [comment] 2018-05-10 14:02
Thanks for the report, @boostninja. I've added it on my list for investigation today. Details are pending.

**Comment by agamzn** [comment] 2018-05-11 15:35
Hey @boostninja,

I'm focusing specifically on us-east-1, because that's where you're reporting this. I've performed a 'manual' build (via our CI/CD tools) against the last 3 AMIs (going back to April 20th). 

Unfortunately, I'm unable to replicate this on my side. As a sanity check, I looked at our pipeline automation that checks all regions and those have been passing lately as well. (The last failure was fixed in commit https://github.com/aws-quickstart/quickstart-linux-bastion/commit/89f891ea57a5d19a2394f6bc6247dc6e0a6dc770 )

Assuming this is consistent for you, are you able to toss over the output of `journalctl | grep -i cloud-init`, and `/var/log/cfn-init-cmd.log`

**Comment by OlexiyTazetdinov** [comment] 2018-06-28 10:47
Any news? I have the same problem using cloudformation on us-west-2.

**Comment by pshemk** [comment] 2018-09-18 00:52
The issue appears only in  aws-cfn-bootstrap-1.4-31:

```
/usr/local/bin/cfn-init -v --stack ppd-mgt-nagiosGw --region ap-southeast-2 --resource rSnmpProxy01a --configsets init
Error occurred during build: Failed to retrieve http://[redacted].s3-ap-southeast-2.amazonaws.com/files/ec2/github_public_key.txt: 'NoneType' object has no attribute 'is_default'
```

If I install the previous version (-30) it works fine and downloads the file. 

Instance metadata:

```
    rSnmpProxy01a:
        Type: "AWS::EC2::Instance"
        Metadata:
            AWS::CloudFormation::Authentication:
                  S3AccessCreds:
                    type: "S3"
                    roleName:
                        Fn::ImportValue:
                            Fn::Sub: "rEC2Base${pVpcName}Role"
            AWS::CloudFormation::Init:
                configSets:
                    init:
                        - setupCfnHup
                        - setupGithubKey
                setupCfnHup:
                    files:
                        "/etc/cfn/cfn-hup.conf":
                            content:
                                Fn::Sub: |
                                    [main]
                                    stack=${AWS::StackId}
                                    region=${AWS::Region}
                                    interval=1
                            mode: '000400'
                            owner: root
                            group: root
                setupGithubKey:
                    files:
                        "/root/.ssh/known_hosts":
                            owner: root
                            group: root
                            source:
                                Fn::Sub: "${pS3TemplatesBucket}files/ec2/github_public_key.txt"
                            authentication: "S3AccessCreds"
                        "/root/github.key":
                            mode: '000400'
                            owner: root
                            group: root
                            source:
                                Fn::Sub: "${pS3TemplatesBucket}files/ec2/${pRepoKeyName}"
                            authentication: "S3AccessCreds"
```

UserData of the EC2 instance:

```
           UserData:
                Fn::Base64:
                    Fn::Sub:
                     - |
                        #!/bin/bash -xe

                        # Install python and ansible
                        apt-get install --reinstall ca-certificates
                        add-apt-repository -y ppa:ansible/ansible
                        apt-get update
                        apt-get install --reinstall ca-certificates
                        apt-get -y install ansible
                        cd /root
                        wget https://bootstrap.pypa.io/get-pip.py
                        python /root/get-pip.py

                        # Install AWS tools
                        pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-1.4-30.tar.gz

                        # Load configuration from Metadata
                        /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource ${pResource} --configsets init

```

If I replace -30 with -31 (or use 'latest') the init script always dies. 

cloud-init logs:

```
Successfully built aws-cfn-bootstrap python-daemon pystache
Installing collected packages: lockfile, python-daemon, pystache, aws-cfn-bootstrap
Successfully installed aws-cfn-bootstrap-1.4 lockfile-0.12.2 pystache-0.5.4 python-daemon-1.6.1
+ /usr/local/bin/cfn-init -v --stack ppd-mgt-nagiosGw --region ap-southeast-2 --resource rSnmpProxy01a --configsets init
Error occurred during build: Failed to retrieve http://[readacted].s3-ap-southeast-2.amazonaws.com/files/ec2/github_public_key.txt: 'NoneType' object has no attribute 'is_default'
Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 running 'modules:final' at Tue, 18 Sep 2018 00:33:59 +0000. Up 27.94 seconds.
2018-09-18 00:34:48,438 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
2018-09-18 00:34:48,452 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2018-09-18 00:34:48,452 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 18.3-9-g2e62cb8a-0ubuntu1~16.04.2 finished at Tue, 18 Sep 2018 00:34:48 +0000. Datasource DataSourceEc2Local.  Up 75.90 seconds
```

**Comment by kubrakjohnsrud** [comment] 2019-04-11 17:45
I can't get either version of ubuntu working, only the amazon linux seems to work. I'm using the EKS quickstart which uses the submodule of the linux bastion quickstart and the vpc quickstart. I'm bringing up a whole environment. I'm doing this in the us-west-2 region. The bastion host starts up and I can log into it, etc but the cloudformation deploy fails.

These are the various errors I've collected from the logs on the bastion host (replaced the stack name with MYSTACKNAME):

**cloud-init-output.log:** 
+ cfn-init -v --stack MYSTACKNAME --resource BastionLaunchConfiguration --region us-west-2
/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Error occurred during build: Command b-bootstrap failed
+ cfn-signal -e 1 --stack MYSTACKNAME --resource BastionAutoScalingGroup --region us-west-2
/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**cfn-init.log:**
2019-04-11 17:17:13,164 [ERROR] Error encountered during build of config: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2019-04-11 17:17:13,165 [ERROR] -----------------------BUILD FAILED!------------------------
2019-04-11 17:17:13,167 [ERROR] Unhandled exception during build: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/EGG-INFO/scripts/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed

**cfn-init-cmd.log:**
2019-04-11 17:17:13,159 P6913 [INFO]    /usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:354: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2019-04-11 17:17:13,159 P6913 [INFO]      SNIMissingWarning
2019-04-11 17:17:13,159 P6913 [INFO]    /usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:354: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2019-04-11 17:17:13,159 P6913 [INFO]      SNIMissingWarning
2019-04-11 17:17:13,159 P6913 [INFO]    /usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:354: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2019-04-11 17:17:13,159 P6913 [INFO]      SNIMissingWarning
2019-04-11 17:17:13,159 P6913 [INFO]    {


If there are other logs or information I can provide please let me know.

**Comment by andrew-glenn** [comment] 2019-04-11 19:40
@kubrakjohnsrud  - I've attempted to reproduce this without much success. If you have the instance up still, would you mind providing the AMI ID used to launch it, and attempt running /tmp/bootstrap_script.sh manually? 

(I'm focusing on 16.04 at 14.04 is EOL and will be removed in the next major update)

**Comment by kubrakjohnsrud** [comment] 2019-04-11 21:13
```
ubuntu@ip-10-110-150-47:/var/log/bastion$ sudo /tmp/./bastion_bootstrap.sh
checkos Ended
verify_dependencies Ended
Setting up bastion session log in /var/log/bastion/bastion.log
ln: failed to create hard link '/var/log/bastion/.bastion.log': File exists
ubuntu@ip-10-110-150-47:/var/log/bastion$ 
```

Can't easily rerun it since it partially ran and created the bastion log file already and made the shell changes.

**Comment by kubrakjohnsrud** [comment] 2019-04-12 14:32
I realize I clipped part of the cfn-init.log which might be relevant. invalid chown might be the culprit?

```
linux-amd64/tiller
linux-amd64/README.md
linux-amd64/helm
linux-amd64/LICENSE
**_chown: invalid user: 'ec2-user'_**

2019-04-11 20:14:00,794 [ERROR] Error encountered during build of config: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2019-04-11 20:14:00,795 [ERROR] -----------------------BUILD FAILED!------------------------
2019-04-11 20:14:00,801 [ERROR] Unhandled exception during build: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/EGG-INFO/scripts/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2019-04-11 20:14:00,951 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-2.amazonaws.com
2019-04-11 20:14:00,951 [DEBUG] Signaling resource BastionAutoScalingGroup in stack MYSTACKNAME with unique ID i-################# and status FAILURE
```

**Comment by andrew-glenn** [comment] 2019-04-12 15:32
@kubrakjohnsrud  - that helped. I realized that the EKS quickstart uses a custom bootstrap script to install additional tooling. I *think* I tracked it down. I need to test a bit. If I'm correct, I'll end up migrating your comments here to an issue in that repo for proper tracking.

**Comment by andrew-glenn** [comment] 2019-04-12 15:36
@kubrakjohnsrud  - see https://github.com/aws-quickstart/quickstart-amazon-eks/issues/29 for further tracking on this. I'll see if I can get a PR submitted to it today.

**Comment by avattathil** [comment] 2019-10-15 22:23
@andrew-glenn adding 16.04 to linux utils is probably the right thing here ?
https://github.com/aws-quickstart/quickstart-linux-utilities/issues/11

**Comment by stephanelogic** [comment] 2021-04-15 01:03
Note on aws-quickstart - for me the banner text was getting passed incorrectly. Parameter needs quotes:
Command b-bootstrap (./bastion_bootstrap.sh --banner **** Authorized users only. All activity is audited **** --enable true
 --tcp-forwarding false --x11-forwarding false) failed

**Comment by tlindsay42** [comment] 2022-12-06 21:51
No longer relevant

**Closed by tlindsay42** 2022-12-06 21:51 UTC
Labels: help wanted
