### ISSUE TITLE
Issues with 'git clone --recurse-submodules' and URL of submodule

### ISSUE THREAD

**Issue by clearvision-support** [aws-quickstart/quickstart-linux-bastion#82] opened 2020-01-30 13:44 UTC
Hi there,
It seems I'm hitting an old issue that was reported on #43:
`Cloning into '/tmp/quickstart-atlassian-jira/submodules/quickstart-atlassian-services/submodules/quickstart-amazon-aurora/submodules/quickstart-linux-bastion'...
git@github.com: Permission denied (publickey).`
`fatal: Could not read from remote repository`

The above was triggered with the following command:
`git clone --recurse-submodules https://github.com/aws-quickstart/quickstart-atlassian-jira.git`

Is there any workaround?
Thank you.

**Comment by nanux** [comment] 2020-02-03 00:17
I believe this is fixed in this PR: https://github.com/aws-quickstart/quickstart-amazon-aurora-postgresql/pull/31

**Comment by andrew-glenn** [comment] 2020-02-04 15:16
@clearvision-support - this will show up per-repo on those that use the linux-bastion (or others) as a submodule. I'm going through our catalog to see what else needs to be changed. I just merged the PR over on the atlassian repo. 

Since the issue isn't fixed directly in this repo, i'm closing this issue.

**Closed by andrew-glenn** 2020-02-04 15:16 UTC
