### ISSUE TITLE
bastion_bootstrap.sh fails on Amazon-Linux2-HVM AMI

### ISSUE THREAD

**Issue by mattyellen** [aws-quickstart/quickstart-linux-bastion#99] opened 2020-07-27 16:05 UTC
Deployed this quickstart with the Amazon-Linux2-HVM AMI.  The `BastionAutoScalingGroup` failed to deploy with:
```
Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

Disabled rollback and checked the instance and in `cfn-init.log` I see:
```
2020-07-27 15:29:15,275 [ERROR] Error encountered during build of config: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2020-07-27 15:29:15,278 [ERROR] -----------------------BUILD FAILED!------------------------
2020-07-27 15:29:15,283 [ERROR] Unhandled exception during build: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
```

In `cfn-init-cmd.log` we can see the problem:
```
2020-07-27 15:29:15,275 P22238 [INFO]           package amazon-cloudwatch-agent-1.246396.0-1.x86_64 is already installed
2020-07-27 15:29:15,275 P22238 [INFO] ------------------------------------------------------------
2020-07-27 15:29:15,275 P22238 [ERROR] Exited with error code 1
```

It appears as though the cloudwatch agent is already installed and `RPM` treats this as an error.
Here are the relevant commands in `bastion_bootstrap.sh`:
```
        curl "https://amazoncloudwatch-agent-${REGION}.s3.${REGION}.${URL_SUFFIX}/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm" -O
        rpm -U ./amazon-cloudwatch-agent.rpm
        rm ./amazon-cloudwatch-agent.rpm
```

Testing this manually:
```
[ec2-user@ip-10-0-20-47 tmp]$ ls
amazon-cloudwatch-agent.rpm  bastion_bootstrap.sh  messages  motd.partTNFWF  motd.WpB9E  systemd-private-6577bb784a8f4db2bbe72e33a87868e3-chronyd.service-aYia7U
[ec2-user@ip-10-0-20-47 tmp]$ sudo rpm -U ./amazon-cloudwatch-agent.rpm
	package amazon-cloudwatch-agent-1.246396.0-1.x86_64 is already installed
[ec2-user@ip-10-0-20-47 tmp]$ echo $?
1
```

Note that adding `--force` works around the issue, but perhaps not the best solution.
```
[ec2-user@ip-10-0-20-47 tmp]$ sudo rpm -U --force ./amazon-cloudwatch-agent.rpm
Redirecting to /bin/systemctl stop amazon-cloudwatch-agent.service
[ec2-user@ip-10-0-20-47 tmp]$ echo $?
0
```

**Comment by struhtanov** [comment] 2022-04-07 10:51
I get the same error when using eks-quickstart with bastion enabled.
So what will be exact steps to workaround this?
If I run that command manually with `--force`, how should I continue stack installation further?

**Comment by troy-ameigh** [comment] 2022-04-07 14:43
The issue in the eks qs is do to something in the custom bootstrap. That current has a fix that is being tested.

**Comment by struhtanov** [comment] 2022-04-07 15:30
> The issue in the eks qs is do to something in the custom bootstrap. That current has a fix that is being tested.

Thanks for a reply. I'm trying to perform steps from here https://aws-quickstart.github.io/quickstart-amazon-eks/ without no modifications. And getting similar error. I'm not customizing bootstrap script for bastion in any way.

**Comment by struhtanov** [comment] 2022-04-07 16:04
I've found out that the reason of failure in my case was in this line:
`chown -R ssm-user:ssm-user /home/ssm-user/.kube/`
ssm-user is missing in aws ec2 instance.

I've commented that line in bastion_bootstrap.sh and was able to successfully setup a cluster.

Not an expert here, just telling which steps helped.

**Comment by tlindsay42** [comment] 2022-12-06 21:48
Confirmed fixed in https://github.com/aws-quickstart/quickstart-amazon-eks/pull/471

**Closed by tlindsay42** 2022-12-06 21:48 UTC
